name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
      with:
        ref: fix-integration
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get -y install python-apt
        python -m pip install --upgrade pip
        pip install flask flask_httpauth pip_api pylint
    - name: Analysing the code with pylint
      run: |
        pylint -dR0914,R0912,R0915,R0401,R0801,E0401,E0402,C0206 apt2sbom/*.py
    - name: Attempting install
      run: |
        pip install .
        echo 'PYTHONPATH=${PYTHONPATH}:/usr/local/lib/python3.9/dist-packages:/usr/local/lib/python3.10/dist-packages:/usr/lib/python3/dist-packages' >> $GITHUB_ENV
        sudo ln -s /usr/lib/python3/dist-packages/apt_pkg.cpython-36m-x86_64-linux-gnu.so /usr/lib/python3/dist-packages/apt_pkg.so
    - name: Try running
      run: |
        apt2sbom -c > /dev/null